# Generated by Django 4.0.4 on 2022-05-29 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ShipmentsApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='Delivery',
        ),
    ]
