# Generated by Django 4.0.4 on 2022-05-29 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ShipmentsApp', '0002_remove_order_delivery'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='Customer',
            new_name='Customer_id',
        ),
    ]
