# Generated by Django 4.0.4 on 2022-05-29 20:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ShipmentsApp', '0003_rename_customer_order_customer_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='Customer_id',
            new_name='Customer',
        ),
        migrations.AlterField(
            model_name='order',
            name='ShippingMethod',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Orders_ship', to='ShipmentsApp.shippingmethod'),
        ),
    ]
