# Generated by Django 4.0.4 on 2022-06-02 06:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ShipmentsApp', '0005_alter_order_customer_alter_order_shippingmethod_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='Customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ShipmentsApp.customer'),
        ),
        migrations.AlterField(
            model_name='order',
            name='ShippingMethod',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='ShipmentsApp.shippingmethod'),
        ),
    ]
